name: PHP CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  php-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, mysqli
          coverage: none

      - name: Verify PHP Version
        run: php -v

      
      - name: PHP Syntax Check
        run: |
          find . -type f -name "*.php" -print0 | while IFS= read -r -d '' file; do
            php -l "$file"
          done
       
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
         php-version: '8.2'

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2


      - name: PHP Syntax Check
        run: find . -name "*.php" -exec php -l {} \;
      
      - name: Run PHPUnit
        run: |
          if [ -f vendor/bin/phpunit ]; then
            vendor/bin/phpunit
          else
            echo "PHPUnit not found, skipping tests."
          fi
